### ISSUE TITLE
Endpoints de restaurantes

### ISSUE THREAD

**Issue by damianfanaro** [igrowker/i002-decamino-back#6]
- Crear el esquema y modelo de restaurante con Mongoose.
- Implementar obtener lista de restaurantes (GET /api/restaurants).
- Implementar obtener detalles de un restaurante específico (GET /api/restaurants/).
- Implementar agregar nuevo restaurante (POST /api/restaurants) [Admin].
- Implementar actualizar información de un restaurante (PUT /api/restaurants/) [Admin].
- Implementar eliminar un restaurante (DELETE /api/restaurants/) [Admin].

**Comment by Andrea-Laurino** [comment]
Se realizaron las 7 solicitudes y me fallaron 2 (PUT Y DELETE). 
Dejo los links a los casos de prueba y el reporte de bug.

El reporte de bug: https://docs.google.com/document/d/1ouduxiZBxoNS6wn7KmY5Fp3ToPrYQ_272pQKQ9ecU_Q/edit?usp=sharing.
Casos de prueba:  https://docs.google.com/spreadsheets/d/1ZNCudYjJFqYx5yNnWuAKhv_VTlyDvN5FkpTgDZNLY0Q/edit?usp=sharing

cuando hagan las correcciones espero que me den aviso asi realizo los correspondientes test de regresión.

**Comment by Andrea-Laurino** [comment]
Ya realice los retest y anda todo muy bien!!
